name: project_naverda
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc:
  animated_text_kit: ^4.2.2
  get:
  flutter_screenutil:
  flutter_bloc:
  hive_flutter:
  hive:
  hive_generator:
  icons_launcher: ^2.1.0
  external_app_launcher:
  slide_countdown: ^0.5.0
  iconsax:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/


  fonts:
     - family: Montserrat-Regular
       fonts:
         - asset: assets/font/Montserrat-Regular.ttf
         - asset: assets/font/Montserrat-Bold.ttf
           weight: 700


     -  family:  Montserrat-SemiBold
        fonts:
          - asset: assets/font/Montserrat-SemiBold.ttf


